In [37]:
# Import numpy
import numpy as np

## Datatypes and attributes


In [38]:
# Numpy's main datatype is ndarray - (n-dimensional array)

# Shape (1,3) - 1 row, 3 columns - one dimension array (vector)
a1 = np.array([1,2,3])

# Shape (2,3) - 1 rows, 3 columns - two dimensional array (matrix)
a2 = np.array([[1,2,3], [4,6.5,7]])

# Shape (3,3,2) - 3 rows, 3 columns, 2 layers - three dimensional array (matrix)
a3 = np.array([[[1,2,3], [4,5,6], [7,8,9]], [[10,11,12],[13,14,15],[16,17,18]]])

In [39]:
# Show shape of array:
a3.shape

(2, 3, 3)

In [40]:
# Show number of dimensions of our arrays:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [41]:
# Show datatypes of our arrays:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [42]:
# Show number of elements in arrays:
a1.size, a2.size, a3.size

(3, 6, 18)

## Creating arrays

In [43]:
# Create a Pandas DataFrame from numpy array
import pandas as pd
df = pd.DataFrame(a2)

In [44]:
# Creating numpy array:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

#### ones()

In [45]:
# ones() function will return a new array of given shape and type filled with ones
ones = np.ones(shape=(2,3), dtype=int)
ones

array([[1, 1, 1],
       [1, 1, 1]])

#### zeroes()

In [46]:
# zeroes() function will return a new array of given shape and type filled with zeros
zeros = np.zeros(shape=(2,3), dtype=float)
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

#### arrange()

In [47]:
# arrange() function to create array from range like start-stop-step
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

#### random.randint()

In [48]:
# random array using random.randint() function to create integers in range from low to high
random_array = np.random.randint(low=0, high=10, size=(3,5))
random_array

array([[3, 5, 8, 8, 7],
       [5, 0, 0, 2, 8],
       [9, 6, 4, 9, 7]])

#### random.random()

In [49]:
# random array using random.random() function to create floats in the half-open interval from 0 to 1
random_array2 = np.random.random((2,3))
random_array2

array([[0.52341258, 0.75040986, 0.66901324],
       [0.46775286, 0.20484909, 0.49076589]])

#### random.rand()

In [50]:
# random array using random.rand() function to create random values in the given shape
random_array3 = np.random.rand(2,3)
random_array3

array([[0.37238469, 0.47740115, 0.36589039],
       [0.83791799, 0.76864751, 0.31399468]])

#### Pseudo-random arrays
#### random.seed()

In [51]:
# Pseudo-random arrays - allows us to create random arrays that are reproducable 
# line below ensures that our random_array4 will be the same no matter how many times we will run this command :) 
np.random.seed(seed=0)
random_array4 = np.random.randint(10, size=(5,3))
random_array4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [52]:
np.random.seed(seed=7)
random_array5 = np.random.random((5,3))
random_array5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

## Viewing arrays and matrices

In [53]:
# Get unique elements of array:
np.unique(random_array4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

#### Indexing

In [67]:
# Access elements by index:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### Slicing

In [69]:
# Access elements by slicing:
a3[0][1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [70]:
a4 = np.random.randint(10. size=(2,3,4,5))

SyntaxError: invalid syntax (1961273450.py, line 1)