In [2]:
# Import numpy
import numpy as np

### Datatypes and attributes


In [3]:
# Numpy's main datatype is ndarray - (n-dimensional array)

# Shape (1,3) - 1 row, 3 columns - one dimension array (vector)
a1 = np.array([1,2,3])

# Shape (2,3) - 1 rows, 3 columns - two dimensional array (matrix)
a2 = np.array([[1,2,3], [4,6.5,7]])

# Shape (3,3,2) - 3 rows, 3 columns, 2 layers - three dimensional array (matrix)
a3 = np.array([[[1,2,3], [4,5,6], [7,8,9]], [[10,11,12],[13,14,15],[16,17,18]]])

In [4]:
# Show shape of array:
a3.shape

(2, 3, 3)

In [5]:
# Show number of dimensions of our arrays:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [6]:
# Show datatypes of our arrays:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [7]:
# Show number of elements in arrays:
a1.size, a2.size, a3.size

(3, 6, 18)

## Creating arrays

In [12]:
# Create a Pandas DataFrame from numpy array
import pandas as pd
df = pd.DataFrame(a2)

In [13]:
# Creating numpy array:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [17]:
# ones() function will return a new array of given shape and type filled with ones
ones = np.ones(shape=(2,3), dtype=int)
ones

array([[1, 1, 1],
       [1, 1, 1]])

In [19]:
# zeroes() function will return a new array of given shape and type filled with zeros
zeros = np.zeros(shape=(2,3), dtype=float)
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
# arrange() function to create array from range like start-stop-step
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [23]:
# random array using random.randint() function to create integers in range from low to high
random_array = np.random.randint(low=0, high=10, size=(3,5))
random_array

array([[7, 4, 4, 7, 0],
       [0, 0, 9, 5, 7],
       [7, 8, 3, 9, 1]])

In [28]:
# random array using random.random() function to create floats in the half-open interval from 0 to 1
random_array2 = np.random.random((2,3))
random_array2

array([[0.13777642, 0.33282493, 0.06925083],
       [0.05026527, 0.6991377 , 0.61513432]])

In [30]:
# random array using random.rand() function to create random values in the given shape
random_array3 = np.random.rand(2,3)
random_array3

array([[0.68284128, 0.48876519, 0.79986118],
       [0.86774647, 0.13287731, 0.5262673 ]])

In [ ]:
# Pseudo-random numbers